import './globals.css';
import type { ReactNode } from 'react';
import type { Metadata } from 'next';
import StyledComponentsRegistry from '../libs/AntdRegistry';

export const metadata: Metadata = {
  title: 'Foundry World Launcher',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="en" className="w-screen h-screen">
      <body className="w-full h-full flex flex-col items-center p-16">
        <h1 className="text-2xl mb-8">Foundry World Launcher</h1>
        <StyledComponentsRegistry>{ children }</StyledComponentsRegistry>
      </body>
    </html>
  );
}
